# Generated by Django 4.2.1 on 2023-05-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='carousel/<django.db.models.fields.SlugField>', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Виден всем')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='categories/<django.db.models.fields.SlugField>', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nutriens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(verbose_name='Калорийность')),
                ('proteins', models.FloatField(verbose_name='Белки')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='categories/<django.db.models.fields.SlugField>', verbose_name='Фото')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('vendor_code', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес, грамм')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Виден всем')),
                ('is_gost', models.BooleanField(verbose_name='Произведён по ГОСТ')),
                ('is_post', models.BooleanField(verbose_name='Постный продукт')),
                ('packaging', models.CharField(max_length=255, verbose_name='Фасовка')),
                ('nutriens', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.nutriens', verbose_name='КБЖУ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producttype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_produc_slug_42f8f6_idx')],
            },
        ),
    ]
