# Generated by Django 4.2.1 on 2023-05-07 13:49

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nutriens_options_remove_product_nutriens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('vendor_code', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('packaging', models.CharField(max_length=255, verbose_name='Фасовка')),
                ('calories', models.FloatField(verbose_name='Калорийность')),
                ('proteins', models.FloatField(verbose_name='Белки')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
            ],
            options={
                'verbose_name': 'Характеристики товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=core.utils.path_category_image, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=core.utils.path_product_image, verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Nutriens',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Товар'),
        ),
    ]
