# Generated by Django 4.2.1 on 2023-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productdetail_remove_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='slug',
        ),
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.CharField(default='нет описания', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='images/carousel/', verbose_name='Изображение'),
        ),
    ]
