# Generated by Django 4.2.1 on 2023-05-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_weight_remove_productdetail_packaging_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackaging',
            options={'verbose_name': 'Фасовка', 'verbose_name_plural': 'Фасовка'},
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='packaging',
            field=models.PositiveIntegerField(verbose_name='Вложение, шт'),
        ),
    ]
