# Generated by Django 4.2.1 on 2023-05-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productpackaging_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_post',
        ),
    ]
