# Generated by Django 4.2.1 on 2023-05-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_is_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='storage_time',
            field=models.PositiveIntegerField(default=6, verbose_name='Срок хранения, месяцев'),
            preserve_default=False,
        ),
    ]
