# Generated by Django 4.2.1 on 2023-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productdetail_storage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='storage_time_units',
            field=models.CharField(choices=[('D', 'дней'), ('M', 'мес')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='storage_time',
            field=models.PositiveIntegerField(verbose_name='Срок хранения'),
        ),
    ]
