# Generated by Django 4.2.1 on 2023-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productdetail_storage_time_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='storage_time_units',
            field=models.CharField(choices=[('D', 'дней'), ('M', 'мес')], default='M', max_length=1, verbose_name=''),
        ),
    ]
