# Generated by Django 4.2.1 on 2023-05-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productdetail_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpackaging',
            old_name='vendor_code',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='core.product', verbose_name='Товар'),
        ),
    ]
