# Generated by Django 4.2.1 on 2023-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_vendor_code_productpackaging_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackaging',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
