# Generated by Django 4.2.1 on 2023-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productpackaging_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
