# Generated by Django 4.2.1 on 2023-05-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productpackaging_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('name',), 'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_slug_42f8f6_idx',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_gost',
            field=models.BooleanField(verbose_name='Соответствует ГОСТ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='storage_time_units',
            field=models.CharField(choices=[('DAYS', 'дней'), ('MOUNTHS', 'мес')], default='MOUNTHS', max_length=7, verbose_name=''),
        ),
    ]
