# Generated by Django 4.2.1 on 2023-05-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='is_active',
            new_name='is_published',
        ),
    ]
