# Generated by Django 4.2.1 on 2023-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_is_active_carousel_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='storage_time_units',
            field=models.CharField(choices=[('DAYS', 'дней'), ('MOUNTHS', 'мес')], default='MOUNTHS', max_length=7, verbose_name='Единицы измерения'),
        ),
    ]
