# Generated by Django 4.2.1 on 2023-06-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
        ('cart', '0003_alter_cart_options_rename_product_sku_cart_sku'),
        ('core', '0017_alter_productdetail_storage_time_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPackaging',
            new_name='ProductPack',
        ),
        migrations.RenameField(
            model_name='productpack',
            old_name='packaging',
            new_name='items_in_box',
        ),
    ]
