# Generated by Django 4.2.1 on 2023-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productpack_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Импорт цен',
                'verbose_name_plural': 'Импорт цен',
                'ordering': ['-date_added'],
            },
        ),
    ]
