# Generated by Django 4.2.1 on 2023-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_priceimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpack',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
