# Generated by Django 4.2.1 on 2023-06-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_alter_cooperation_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperation',
            old_name='person',
            new_name='name',
        ),
    ]
