# Generated by Django 4.2.1 on 2023-05-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['sku__product__name']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_sku',
            new_name='sku',
        ),
    ]
