# Generated by Django 4.2.1 on 2023-06-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_rename_product_sku_cart_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['pack__product__name']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='sku',
            new_name='pack',
        ),
    ]
