# Generated by Django 4.2.1 on 2023-06-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productpack_product'),
        ('cart', '0004_alter_cart_options_rename_sku_cart_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='core.productpack', verbose_name='Фасовка'),
        ),
    ]
