# Generated by Django 4.2.1 on 2023-05-29 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('36d301db-0eaa-4b36-983c-59c56d42d5ce')),
        ),
    ]
