# Generated by Django 4.2.1 on 2023-06-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productpack_product'),
        ('orders', '0005_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_743fca_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='core.productpack', verbose_name='Фасовка'),
        ),
    ]
